"""empty message

Revision ID: 299fb2c98616
Revises: 0053931575a9
Create Date: 2017-12-03 11:13:40.888205

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '299fb2c98616'
down_revision = '0053931575a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'author_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('answer', 'question_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'question_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('answer', 'author_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
