"""empty message

Revision ID: 5324a7f30d43
Revises: 299fb2c98616
Create Date: 2017-12-03 11:59:25.652118

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5324a7f30d43'
down_revision = '299fb2c98616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'author_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('answer', 'question_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('answer', 'question_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('answer', 'author_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
